MagiskMountReSizeIMG v3.0
Signed-off-by: Dark❶ <dark-1@users.noreply.github.com>

diff --git a/META-INF/com/google/android/update-binary b/META-INF/com/google/android/update-binary
--- a/META-INF/com/google/android/update-binary
+++ b/META-INF/com/google/android/update-binary
@@ -18,86 +18,57 @@
 # 
 ##########################################################################################
 
-# Detect whether in boot mode
-ps | grep zygote | grep -v grep >/dev/null && BOOTMODE=true || BOOTMODE=false
-$BOOTMODE || ps -A 2>/dev/null | grep zygote | grep -v grep >/dev/null && BOOTMODE=true
-
-# This path should work in any cases
 TMPDIR=/dev/tmp
-MOUNTPATH=/magisk
-IMG=/data/magisk.img
-if $BOOTMODE; then
-  MOUNTPATH=/dev/magisk_merge
-  IMG=/data/magisk_merge.img
-fi
-
-MRIDIR=$TMPDIR/mridir
-MAGISKBIN=/data/magisk
+INSTALLER=$TMPDIR/install
+# Always mount under tmp
+MOUNTPATH=$TMPDIR/magisk_img
 
 # Default permissions
 umask 022
 
 # Initial cleanup
 rm -rf $TMPDIR 2>/dev/null
+mkdir -p $INSTALLER
 
-mkdir -p $MRIDIR
+# echo before loading util_functions
+ui_print() { echo "$1"; }
+
+require_new_magisk() {
+  ui_print "*******************************"
+  ui_print " Please install Magisk v17.0+! "
+  ui_print "*******************************"
+  exit 1
+}
 
 ##########################################################################################
-# Flashable update-binary preparation
+# Environment
 ##########################################################################################
 
 OUTFD=$2
 ZIP=$3
 
-readlink /proc/$$/fd/$OUTFD 2>/dev/null | grep /tmp >/dev/null
-if [ "$?" -eq "0" ]; then
-  OUTFD=0
-  for FD in `ls /proc/$$/fd`; do
-    readlink /proc/$$/fd/$FD 2>/dev/null | grep pipe >/dev/null
-    if [ "$?" -eq "0" ]; then
-      ps | grep " 3 $FD " | grep -v grep >/dev/null
-      if [ "$?" -eq "0" ]; then
-        OUTFD=$FD
-        break
-      fi
-    fi
-  done
+mount /data 2>/dev/null
+
+# Load utility functions
+if [ -f /data/adb/magisk/util_functions.sh ]; then
+  . /data/adb/magisk/util_functions.sh
+elif [ -f /data/magisk/util_functions.sh ]; then
+  NVBASE=/data
+  . /data/magisk/util_functions.sh
+else
+  require_new_magisk
 fi
 
-ui_print() {
-  if $BOOTMODE; then
-    echo "$1"
-  else
-    echo -n -e "ui_print $1\n" >> /proc/self/fd/$OUTFD
-    echo -n -e "ui_print\n" >> /proc/self/fd/$OUTFD
-  fi
-}
+# Use alternative image if in BOOTMODE
+$BOOTMODE && IMG=$NVBASE/magisk_merge.img
 
-require_new_magisk() {
-  ui_print "***********************************"
-  ui_print "! $MAGISKBIN isn't setup properly !"
-  ui_print "!  Please install Magisk v14.0+   !"
-  ui_print "***********************************"
-  exit 1
-}
+# Preperation for flashable zips
+setup_flashable
 
-ui_print "- Mounting /system, /vendor, /data, /cache"
-mount -o ro /system 2>/dev/null
-mount -o ro /vendor 2>/dev/null
-mount /data 2>/dev/null
-mount /cache 2>/dev/null
+# Mount partitions
+mount_partitions
 
-# MAGISKBIN must exist, binaries and utility functions are placed there
-[ -d $MAGISKBIN -a -f $MAGISKBIN/magisk -a -f $MAGISKBIN/util_functions.sh ] || require_new_magisk
-
-# Load utility fuctions
-. $MAGISKBIN/util_functions.sh
-
-# Check for Magisk
-[ ! -f $IMG ] && abort "!!! Magisk is not Installed!"
-$BOOTMODE && ! is_mounted /magisk && abort "!!! Magisk is not activated!"
-
-# We need busybox/binaries to be setup
+# Setup busybox and binaries
 $BOOTMODE && boot_actions || recovery_actions
 
 ##########################################################################################
@@ -108,12 +79,11 @@ $BOOTMODE && boot_actions || recovery_actions
 DeBugInfo=false
 
 # Extract configurations file
+unzip -o "$ZIP" config.sh -d $INSTALLER >&2
 
-unzip -o "$ZIP" config.sh -d $MRIDIR 2>/dev/null
-[ ! -f $MRIDIR/config.sh ] && abort "!!! Unable to extract zip file!"
-
+[ ! -f $INSTALLER/config.sh ] && abort "! Unable to extract zip file!"
 # Load configurations
-. $MRIDIR/config.sh
+. $INSTALLER/config.sh
 
 ###########################################
 ## Function's                            ##
@@ -135,7 +105,7 @@ image_resize()
     0 )
         # Just InFo for Magisk IMG
         ui_print "- In \"$ReSizeMode\" ReSizeMode"
-        image_size_check $ReSizeIMG
+        check_filesystem $ReSizeIMG $MOUNTPATH
         ui_print "- ----"
         ui_print "- InFo for Magisk IMG \"$ReSizeIMG\""
         ui_print "- Free  Size = $curFreeM M"
@@ -147,10 +117,10 @@ image_resize()
     1 )
         # ReSize to Default 64M OR MoRe Depending on Current Used Size
         ui_print "- In \"$ReSizeMode\" ReSizeMode"
-        image_size_check $ReSizeIMG
+        check_filesystem $ReSizeIMG $MOUNTPATH
         local MinSize=$((curUsedM / 32 * 32 + 64))
         ui_print "- ReSizeing \"$ReSizeIMG\" to ${MinSize} M "
-        $MAGISKBIN/magisk --resizeimg $ReSizeIMG $MinSize
+        $MAGISKBIN/magisk imgtool resize $ReSizeIMG $MinSize >&2
         $DeBugInfo && ui_print "- Done ReSizeIMG'ing"
       ;;
     2 )
@@ -159,11 +129,11 @@ image_resize()
         $DeBugInfo && ui_print "- ReSizeUserMB before Convert is $ReSizeUserMB"
         ReSizeUserMB=${ReSizeUserMB%%.*} && ReSizeUserMB=${ReSizeUserMB##*-} && ReSizeUserMB=$((ReSizeUserMB / 4 * 4))
         $DeBugInfo && ui_print "- ReSizeUserMB after Convert is $ReSizeUserMB"
-        image_size_check $ReSizeIMG
+        check_filesystem $ReSizeIMG $MOUNTPATH
         if [ $ReSizeUserMB -gt 64 ] && [ $ReSizeUserMB -gt $curUsedM ] ; 
         then
           ui_print "- ReSizeing \"$ReSizeIMG\" to ${ReSizeUserMB} M "
-          $MAGISKBIN/magisk --resizeimg $ReSizeIMG $ReSizeUserMB
+          $MAGISKBIN/magisk imgtool resize $ReSizeIMG $ReSizeUserMB >&2
         else
           ui_print "! Did Not ReSize !" 
           ui_print "! Due to \"$ReSizeUserMB\" is Either Less-Than \"64\" OR \"$curUsedM\" !" 
@@ -178,13 +148,13 @@ image_resize()
         $DeBugInfo && ui_print "- ReSizeUserMB before Convert is $ReSizeUserMB"
         ReSizeUserMB=${ReSizeUserMB%%.*} && ReSizeUserMB=$((ReSizeUserMB / 4 * 4))
         $DeBugInfo && ui_print "- ReSizeUserMB after Convert is $ReSizeUserMB"
-        image_size_check $ReSizeIMG
+        check_filesystem $ReSizeIMG $MOUNTPATH
         local NEWsizeMB=$((curSizeM + ReSizeUserMB))
         if [ $NEWsizeMB -gt 64 ] && [ $NEWsizeMB -gt $curUsedM ] ; 
         then
           ui_print "- Since \"$curSizeM\" + \"$ReSizeUserMB\" = \"$NEWsizeMB\"" 
           ui_print "- ReSizeing \"$ReSizeIMG\" to ${NEWsizeMB} M "
-          $MAGISKBIN/magisk --resizeimg $ReSizeIMG $NEWsizeMB
+          $MAGISKBIN/magisk imgtool resize $ReSizeIMG $NEWsizeMB >&2
         else
           ui_print "! Did Not ReSize !" 
           ui_print "! Since \"$curSizeM\" + \"$ReSizeUserMB\" = \"$NEWsizeMB\"!" 
@@ -258,7 +228,7 @@ then
     ui_print "! \"$IMG\" Mounted Hence UnMounting to ReSize"
     local DEVLOOP=`cat /proc/mounts | grep " $MOUNTPATH " | head -n 1 | cut -c -16`
     $DeBugInfo && ui_print "- Detaching \"$DEVLOOP\""
-    $MAGISKBIN/magisk --umountimg $MOUNTPATH $DEVLOOP
+    $MAGISKBIN/magisk imgtool umount $MOUNTPATH $DEVLOOP
     # Check if Still Mount'ed
     is_mounted $MOUNTPATH && abort "! \"$IMG\" Unmount Failed!..."
     rmdir $MOUNTPATH
@@ -274,7 +244,7 @@ then
   ui_print "- Magisk Mount IMG Mode [MTSW]"
   image_resize $IMG $MTRSMO $MTRSMB
   ui_print "- Mounting $IMG to $MOUNTPATH"
-  local MAGISKLOOP=`$MAGISKBIN/magisk --mountimg $IMG $MOUNTPATH`
+  local MAGISKLOOP=`$MAGISKBIN/magisk imgtool mount $IMG $MOUNTPATH`
   # Check if Not Mount'ed
   is_mounted $MOUNTPATH || abort "! \"$IMG\" Mount on \"$MAGISKLOOP\" failed..."
   ui_print "- \"$IMG\" Mounted on DevLoop = $MAGISKLOOP"
@@ -287,7 +257,7 @@ then
   ui_print "- UnMounting $MOUNTPATH from $IMG"
   local DEVLOOP=`cat /proc/mounts | grep " $MOUNTPATH " | head -n 1 | cut -c -16`
   ui_print "- Detaching \"$DEVLOOP\""
-  $MAGISKBIN/magisk --umountimg $MOUNTPATH $DEVLOOP
+  $MAGISKBIN/magisk imgtool umount $MOUNTPATH $DEVLOOP
   # Check if Still Mount'ed
   is_mounted $MOUNTPATH && abort "! \"$IMG\" Unmount Failed!..."
   rmdir $MOUNTPATH
@@ -314,5 +284,6 @@ $DeBugInfo && ui_print "- Finalizing ..."
 $BOOTMODE || recovery_cleanup
 $DeBugInfo && ui_print "- Before ReMove $TMPDIR"
 rm -rf $TMPDIR
+
 ui_print "- Done"
 exit 0
